services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kaban-database
      POSTGRES_USER: kaban-user
      POSTGRES_PASSWORD: kaban-password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
